version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: zlast_date
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - c:\Users\ies01\Documents\GitHub\zlastdate\www:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=zlastdate
      - MYSQL_DATABASE=zlastdate

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
  
    environment:
      - MYSQL_USERNAME:root
      - MYSQL_ROOT_PASSWORD=zlastdate

   
    ports:
      - '8080:80'